name: "build-dcevm manually "
on:
  workflow_dispatch:
    inputs:
      dcevm_branch:
        description: 'dcevm branch'
        required: true
        default: 'trava-jdk-8-dcevm'
      dcevm_tag:
        description: 'dcevm tag'
        required: true
        default: 'dcevm8u282b09'

jobs:
  dcevm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        javaToBuild: [jdk8u]
    steps:
    - uses: actions/checkout@v1
    - name: Before cooking
      id: before_cook
      shell: cmd
      run: |
        choco install cygwin
        choco install vs2013sdk
        C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,unzip,automake,autoconf,zip
        git config --system core.longpaths true; git config --global core.autocrlf false
        unset -v _JAVA_OPTIONS
        git clone --depth 1 --branch travaopenjdk https://github.com/TravaOpenJDK/openjdk-build.git
    - name: Begin cooking
      id: cook
      shell: cmd
      run: |
        export JDK8_BOOT_DIR="$PWD/openjdk-build/jdk-8"
        export HSWAP_AGENT_DOWNLOAD_URL=https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.4.1/hotswap-agent-1.4.1.jar
        mkdir -p "$JDK8_BOOT_DIR"
        powershell -Command "C:\tools\cygwin\bin\bash.exe -c './build_windows.sh'"; 
    - uses: actions/upload-artifact@v2
      with:
        name: '${{ steps.buildJDK.outputs.JdkPackageFileName }}'
        path: ${{ github.workspace }}/temurin-build-dcevm/workspace/artifacts/${{ steps.buildJDK.outputs.JdkPackageFileName }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/temurin-build-dcevm/workspace/artifacts/${{ steps.buildJDK.outputs.JdkPackageFileName }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
